import type { Metadata } from "next";
import { Orbitron } from "next/font/google";
import "./globals.css";
import Head from "@/components/Layout/Head";
import Footer from "@/components/Layout/Footer";
import { Analytics } from "@vercel/analytics/react";
import { useEffect } from "react";
import HeroSection from "@/components/Layout/HeroSection";

const inter = Orbitron({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>MARVELL</title>
      </head>
      <body className={inter.className} style={{ overflowX: "hidden" }}>
        <div id="hero">
          <HeroSection />
        </div>
        <Head />
        <main>
          {children}
          <Analytics />
        </main>
        <Footer />
      </body>
    </html>
  );
}
