import type { Metadata } from "next";
import { Orbitron } from "next/font/google";
import "./globals.css";
import Head from "@/components/Layout/Head";
import Footer from "@/components/Layout/Footer";


const inter = Orbitron({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Head />
        <main>{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
